/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AppRouteImport } from './routes/_app'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicSignupRouteImport } from './routes/_public/signup'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as AppStatsRouteImport } from './routes/_app/stats'
import { Route as AppRoomRouteImport } from './routes/_app/room'
import { Route as AppQuestsRouteImport } from './routes/_app/quests'
import { Route as AppOnboardingRouteImport } from './routes/_app/onboarding'
import { Route as AppLibraryRouteImport } from './routes/_app/library'
import { Route as PublicOauthCallbackRouteImport } from './routes/_public/oauth.callback'
import { Route as AppReaderPdfIdRouteImport } from './routes/_app/reader.$pdfId'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSignupRoute = PublicSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const AppStatsRoute = AppStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AppRoute,
} as any)
const AppRoomRoute = AppRoomRouteImport.update({
  id: '/room',
  path: '/room',
  getParentRoute: () => AppRoute,
} as any)
const AppQuestsRoute = AppQuestsRouteImport.update({
  id: '/quests',
  path: '/quests',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const PublicOauthCallbackRoute = PublicOauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => PublicRoute,
} as any)
const AppReaderPdfIdRoute = AppReaderPdfIdRouteImport.update({
  id: '/reader/$pdfId',
  path: '/reader/$pdfId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/library': typeof AppLibraryRoute
  '/onboarding': typeof AppOnboardingRoute
  '/quests': typeof AppQuestsRoute
  '/room': typeof AppRoomRoute
  '/stats': typeof AppStatsRoute
  '/login': typeof PublicLoginRoute
  '/signup': typeof PublicSignupRoute
  '/reader/$pdfId': typeof AppReaderPdfIdRoute
  '/oauth/callback': typeof PublicOauthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/library': typeof AppLibraryRoute
  '/onboarding': typeof AppOnboardingRoute
  '/quests': typeof AppQuestsRoute
  '/room': typeof AppRoomRoute
  '/stats': typeof AppStatsRoute
  '/login': typeof PublicLoginRoute
  '/signup': typeof PublicSignupRoute
  '/reader/$pdfId': typeof AppReaderPdfIdRoute
  '/oauth/callback': typeof PublicOauthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_app/library': typeof AppLibraryRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/quests': typeof AppQuestsRoute
  '/_app/room': typeof AppRoomRoute
  '/_app/stats': typeof AppStatsRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/signup': typeof PublicSignupRoute
  '/_public/': typeof PublicIndexRoute
  '/_app/reader/$pdfId': typeof AppReaderPdfIdRoute
  '/_public/oauth/callback': typeof PublicOauthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/library'
    | '/onboarding'
    | '/quests'
    | '/room'
    | '/stats'
    | '/login'
    | '/signup'
    | '/reader/$pdfId'
    | '/oauth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/library'
    | '/onboarding'
    | '/quests'
    | '/room'
    | '/stats'
    | '/login'
    | '/signup'
    | '/reader/$pdfId'
    | '/oauth/callback'
  id:
    | '__root__'
    | '/_app'
    | '/_public'
    | '/_app/library'
    | '/_app/onboarding'
    | '/_app/quests'
    | '/_app/room'
    | '/_app/stats'
    | '/_public/login'
    | '/_public/signup'
    | '/_public/'
    | '/_app/reader/$pdfId'
    | '/_public/oauth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/signup': {
      id: '/_public/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof PublicSignupRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_app/stats': {
      id: '/_app/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AppStatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/room': {
      id: '/_app/room'
      path: '/room'
      fullPath: '/room'
      preLoaderRoute: typeof AppRoomRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quests': {
      id: '/_app/quests'
      path: '/quests'
      fullPath: '/quests'
      preLoaderRoute: typeof AppQuestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library': {
      id: '/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_public/oauth/callback': {
      id: '/_public/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof PublicOauthCallbackRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_app/reader/$pdfId': {
      id: '/_app/reader/$pdfId'
      path: '/reader/$pdfId'
      fullPath: '/reader/$pdfId'
      preLoaderRoute: typeof AppReaderPdfIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppLibraryRoute: typeof AppLibraryRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppQuestsRoute: typeof AppQuestsRoute
  AppRoomRoute: typeof AppRoomRoute
  AppStatsRoute: typeof AppStatsRoute
  AppReaderPdfIdRoute: typeof AppReaderPdfIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppLibraryRoute: AppLibraryRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppQuestsRoute: AppQuestsRoute,
  AppRoomRoute: AppRoomRoute,
  AppStatsRoute: AppStatsRoute,
  AppReaderPdfIdRoute: AppReaderPdfIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicSignupRoute: typeof PublicSignupRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicOauthCallbackRoute: typeof PublicOauthCallbackRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicSignupRoute: PublicSignupRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicOauthCallbackRoute: PublicOauthCallbackRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
